import type { CatalogEntry } from './types';

export const DRINKS: readonly CatalogEntry[] = [
  // water
  ['Water', 'Woda'],
  ['Still water', 'Woda niegazowana'],
  ['Sparkling water', 'Woda gazowana'],
  ['Lightly sparkling water', 'Woda lekko gazowana'],
  ['Spring water', 'Woda źródlana'],
  ['Flavoured water', 'Woda smakowa'],
  ['Coconut water', 'Woda kokosowa'],
  ['Tonic water', 'Tonik'],

  // juice
  ['Apple juice', 'Sok jabłkowy'],
  ['Pressed apple juice', 'Sok jabłkowy tłoczony'],
  ['Orange juice', 'Sok pomarańczowy'],
  ['Multifruit juice', 'Sok wieloowocowy'],
  ['Multivitamin juice', 'Sok multiwitamina'],
  ['Grapefruit juice', 'Sok grejpfrutowy'],
  ['Pineapple juice', 'Sok ananasowy'],
  ['Tomato juice', 'Sok pomidorowy'],
  ['Carrot juice', 'Sok marchwiowy'],
  ['Beetroot juice', 'Sok z buraka'],
  ['Blackcurrant juice', 'Sok z czarnej porzeczki'],
  ['Cranberry juice', 'Sok żurawinowy'],
  ['Lemon juice', 'Sok z cytryny'],
  ['Fruit smoothie', 'Smoothie owocowe'],
  ['Fruit drink', 'Napój owocowy'],

  // soft drinks
  ['Cola', 'Cola'],
  ['Lemonade', 'Lemoniada'],
  ['Orange soda', 'Oranżada'],
  ['Lemon-lime soda', 'Napój cytrynowo-limonkowy', 'sprite'],
  ['Fizzy drink', 'Napój gazowany'],
  ['Iced tea', 'Ice tea'],
  ['Kvass', 'Kwas chlebowy'],
  ['Kombucha', 'Kombucha'],
  ['Isotonic drink', 'Napój izotoniczny', 'izotonik'],
  ['Energy drink', 'Napój energetyczny'],

  // plant drinks
  ['Oat drink', 'Napój owsiany'],
  ['Soy drink', 'Napój sojowy'],
  ['Almond drink', 'Napój migdałowy'],
  ['Rice drink', 'Napój ryżowy'],
  ['Coconut drink', 'Napój kokosowy'],

  // coffee
  ['Coffee', 'Kawa'],
  ['Coffee beans', 'Kawa ziarnista'],
  ['Ground coffee', 'Kawa mielona'],
  ['Instant coffee', 'Kawa rozpuszczalna', 'nescafe'],
  ['Coffee mix sachets', 'Kawa 3w1'],
  ['Cappuccino sachets', 'Cappuccino w saszetkach'],
  ['Coffee capsules', 'Kapsułki do kawy'],
  ['Decaf coffee', 'Kawa bezkofeinowa'],
  ['Coffee substitute', 'Kawa zbożowa', 'inka'],
  ['Coffee creamer', 'Zabielacz do kawy'],

  // tea and cocoa
  ['Tea', 'Herbata'],
  ['Black tea', 'Herbata czarna'],
  ['Green tea', 'Herbata zielona'],
  ['Earl Grey tea', 'Herbata earl grey'],
  ['Fruit tea', 'Herbata owocowa'],
  ['Raspberry tea', 'Herbata malinowa'],
  ['Herbal tea', 'Herbata ziołowa'],
  ['Peppermint tea', 'Herbata miętowa'],
  ['Chamomile tea', 'Rumianek', 'herbata'],
  ['Nettle tea', 'Pokrzywa', 'herbata'],
  ['Linden tea', 'Herbata z lipy'],
  ['Loose leaf tea', 'Herbata liściasta'],
  ['Rooibos', 'Rooibos'],
  ['Matcha', 'Matcha'],
  ['Yerba mate', 'Yerba mate'],
  ['Cocoa', 'Kakao'],
  ['Hot chocolate', 'Gorąca czekolada'],

  // beer and cider
  ['Beer', 'Piwo'],
  ['Lager', 'Piwo jasne'],
  ['Dark beer', 'Piwo ciemne'],
  ['Wheat beer', 'Piwo pszeniczne'],
  ['Craft beer', 'Piwo rzemieślnicze'],
  ['Porter', 'Porter'],
  ['Non-alcoholic beer', 'Piwo bezalkoholowe'],
  ['Radler', 'Radler'],
  ['Cider', 'Cydr'],

  // wine
  ['Red wine', 'Wino czerwone'],
  ['White wine', 'Wino białe'],
  ['Rosé wine', 'Wino różowe'],
  ['Sparkling wine', 'Wino musujące'],
  ['Prosecco', 'Prosecco'],
  ['Champagne', 'Szampan'],
  ['Mead', 'Miód pitny'],

  // spirits
  ['Vodka', 'Wódka'],
  ['Whisky', 'Whisky', 'whiskey'],
  ['Rum', 'Rum'],
  ['Gin', 'Gin'],
  ['Brandy', 'Brandy'],
  ['Cognac', 'Koniak'],
  ['Tequila', 'Tequila'],
  ['Vermouth', 'Wermut'],
  ['Liqueur', 'Likier'],
  ['Cream liqueur', 'Likier śmietankowy'],
  ['Advocaat', 'Adwokat'],
  ['Rectified spirit', 'Spirytus'],
];
