import type { CatalogEntry } from './types';

export const HOME: readonly CatalogEntry[] = [
  // dishes
  ['Dish soap', 'Płyn do naczyń'],
  ['Dishwasher tablets', 'Tabletki do zmywarki'],
  ['Dishwasher salt', 'Sól do zmywarki'],
  ['Rinse aid', 'Nabłyszczacz do zmywarki'],
  ['Dishwasher cleaner', 'Środek do czyszczenia zmywarki'],
  ['Sponges', 'Gąbki do naczyń'],
  ['Scouring pads', 'Druciaki'],
  ['Dish cloths', 'Ścierki do naczyń'],
  ['Microfibre cloths', 'Ściereczki z mikrofibry'],

  // laundry
  ['Laundry capsules', 'Kapsułki do prania'],
  ['Laundry powder', 'Proszek do prania'],
  ['Laundry liquid', 'Płyn do prania'],
  ['Fabric softener', 'Płyn do płukania'],
  ['Stain remover', 'Odplamiacz'],
  ['Bleach', 'Wybielacz'],
  ['Colour catcher sheets', 'Chusteczki wyłapujące kolor'],
  ['Descaler', 'Odkamieniacz'],
  ['Washing machine cleaner', 'Środek do czyszczenia pralki'],

  // cleaning
  ['All-purpose cleaner', 'Płyn uniwersalny'],
  ['Floor cleaner', 'Płyn do podłóg'],
  ['Window cleaner', 'Płyn do szyb'],
  ['Bathroom cleaner', 'Płyn do łazienki'],
  ['Kitchen cleaner', 'Płyn do kuchni'],
  ['Toilet cleaner', 'Płyn do WC'],
  ['Toilet block', 'Zawieszka do WC'],
  ['Oven cleaner', 'Środek do piekarnika'],
  ['Drain cleaner', 'Środek do udrażniania rur'],
  ['Scouring cream', 'Mleczko do czyszczenia'],
  ['Disinfectant', 'Środek dezynfekujący'],
  ['Furniture polish', 'Płyn do mebli'],
  ['Cleaning wipes', 'Chusteczki do czyszczenia'],
  ['Air freshener', 'Odświeżacz powietrza'],
  ['Floor cloths', 'Ścierki do podłogi'],
  ['Rubber gloves', 'Rękawice gumowe'],
  ['Disposable gloves', 'Rękawiczki jednorazowe'],

  // paper, bags and wraps
  ['Toilet paper', 'Papier toaletowy'],
  ['Paper towels', 'Ręczniki papierowe'],
  ['Tissues', 'Chusteczki higieniczne', 'kleenex'],
  ['Napkins', 'Serwetki'],
  ['Bin bags', 'Worki na śmieci'],
  ['Compostable bags', 'Worki biodegradowalne'],
  ['Kitchen foil', 'Folia aluminiowa', 'alufolia'],
  ['Cling film', 'Folia spożywcza'],
  ['Baking paper', 'Papier do pieczenia', 'pergamin'],
  ['Freezer bags', 'Torebki strunowe'],
  ['Sandwich bags', 'Woreczki śniadaniowe'],
  ['Coffee filters', 'Filtry do kawy'],
  ['Cupcake cases', 'Papilotki'],

  // tableware
  ['Paper plates', 'Talerze papierowe'],
  ['Paper cups', 'Kubki papierowe'],
  ['Disposable cutlery', 'Sztućce jednorazowe'],
  ['Straws', 'Słomki'],
  ['Toothpicks', 'Wykałaczki'],

  // teeth, hair, body
  ['Toothpaste', 'Pasta do zębów'],
  ['Toothbrush', 'Szczoteczka do zębów'],
  ['Mouthwash', 'Płyn do płukania jamy ustnej'],
  ['Dental floss', 'Nić dentystyczna'],
  ['Shampoo', 'Szampon'],
  ['Conditioner', 'Odżywka do włosów'],
  ['Hair spray', 'Lakier do włosów'],
  ['Shower gel', 'Żel pod prysznic'],
  ['Bath foam', 'Płyn do kąpieli'],
  ['Soap', 'Mydło'],
  ['Liquid soap', 'Mydło w płynie'],
  ['Deodorant', 'Dezodorant'],
  ['Razors', 'Maszynki do golenia'],
  ['Shaving foam', 'Pianka do golenia'],
  ['Body lotion', 'Balsam do ciała'],
  ['Hand cream', 'Krem do rąk'],
  ['Face cream', 'Krem do twarzy'],
  ['Sunscreen', 'Krem z filtrem'],
  ['Lip balm', 'Pomadka ochronna'],
  ['Micellar water', 'Płyn micelarny'],
  ['Cotton pads', 'Płatki kosmetyczne', 'waciki'],
  ['Cotton buds', 'Patyczki higieniczne'],
  ['Hand sanitiser', 'Płyn do dezynfekcji rąk'],
  ['Wet wipes', 'Chusteczki nawilżane'],
  ['Sanitary pads', 'Podpaski'],
  ['Tampons', 'Tampony'],
  ['Panty liners', 'Wkładki higieniczne'],

  // baby and pets
  ['Nappies', 'Pieluchy', 'diapers pampers'],
  ['Baby wipes', 'Chusteczki dla niemowląt'],
  ['Cat food', 'Karma dla kota'],
  ['Dog food', 'Karma dla psa'],
  ['Cat litter', 'Żwirek dla kota'],
  ['Dog treats', 'Przysmaki dla psa'],

  // bulbs, batteries, fire
  ['Batteries AA', 'Baterie AA'],
  ['Batteries AAA', 'Baterie AAA'],
  ['Light bulbs', 'Żarówki'],
  ['LED bulbs', 'Żarówki LED'],
  ['Candles', 'Świeczki', 'swiece'],
  ['Tealights', 'Podgrzewacze'],
  ['Matches', 'Zapałki'],
  ['Lighter', 'Zapalniczka'],
  ['Charcoal', 'Węgiel drzewny', 'brykiet'],
  ['Firelighters', 'Rozpałka do grilla'],
  ['Mosquito repellent', 'Środek na komary'],
];
