import type { CatalogEntry } from './types';

export const MEAT: readonly CatalogEntry[] = [
  // chicken
  ['Chicken breast', 'Pierś z kurczaka', 'filet'],
  ['Chicken tenderloins', 'Polędwiczki z kurczaka'],
  ['Chicken thighs', 'Udka z kurczaka', 'udko'],
  ['Chicken thigh fillets', 'Filety z udka kurczaka'],
  ['Chicken drumsticks', 'Podudzia z kurczaka'],
  ['Chicken wings', 'Skrzydełka z kurczaka'],
  ['Chicken leg quarters', 'Ćwiartki z kurczaka'],
  ['Whole chicken', 'Kurczak cały'],
  ['Chicken carcass', 'Korpus z kurczaka'],
  ['Chicken liver', 'Wątróbka drobiowa'],
  ['Chicken hearts', 'Serca drobiowe'],
  ['Chicken gizzards', 'Żołądki drobiowe'],
  ['Minced chicken', 'Mięso mielone z kurczaka'],

  // turkey, duck, game
  ['Turkey breast', 'Pierś z indyka'],
  ['Turkey thighs', 'Udka z indyka'],
  ['Turkey drumsticks', 'Podudzia z indyka'],
  ['Minced turkey', 'Mięso mielone z indyka'],
  ['Whole duck', 'Kaczka cała'],
  ['Duck breast', 'Pierś z kaczki'],
  ['Duck legs', 'Udka z kaczki'],
  ['Goose', 'Gęś'],
  ['Rabbit', 'Królik'],
  ['Venison', 'Dziczyzna'],

  // pork
  ['Pork loin', 'Schab'],
  ['Pork chops', 'Kotlety schabowe'],
  ['Pork neck', 'Karkówka'],
  ['Pork shoulder', 'Łopatka wieprzowa'],
  ['Pork leg', 'Udziec wieprzowy'],
  ['Pork tenderloin', 'Polędwiczka wieprzowa'],
  ['Pork ribs', 'Żeberka'],
  ['Pork knuckle', 'Golonka'],
  ['Smoked pork knuckle', 'Golonka wędzona'],
  ['Pork belly', 'Boczek surowy'],
  ['Pork trotters', 'Nóżki wieprzowe'],
  ['Pork liver', 'Wątroba wieprzowa'],
  ['Pork fat', 'Słonina'],

  // beef and lamb
  ['Beef', 'Wołowina'],
  ['Beef steak', 'Stek wołowy'],
  ['Ribeye', 'Antrykot'],
  ['Beef tenderloin', 'Polędwica wołowa'],
  ['Sirloin', 'Rostbef'],
  ['Beef for stew', 'Mięso na gulasz'],
  ['Beef shank', 'Szponder'],
  ['Beef ribs', 'Żeberka wołowe'],
  ['Beef brisket', 'Mostek wołowy'],
  ['Beef roast', 'Pieczeń wołowa'],
  ['Beef liver', 'Wątroba wołowa'],
  ['Oxtail', 'Ogon wołowy'],
  ['Beef bones', 'Kości wołowe'],
  ['Veal', 'Cielęcina'],
  ['Veal escalopes', 'Sznycle cielęce'],
  ['Lamb', 'Jagnięcina'],

  // minced and ready to cook
  ['Minced pork', 'Mięso mielone'],
  ['Minced beef', 'Mięso mielone wołowe'],
  ['Mixed mince', 'Mięso mielone wieprzowo-wołowe'],
  ['Meatballs', 'Pulpety'],
  ['Minced meat patties', 'Kotlety mielone'],
  ['Beef burger patties', 'Burgery wołowe'],
  ['Raw sausages', 'Kiełbaski surowe'],
  ['Grilling sausages', 'Kiełbaski na grilla'],

  // sausages
  ['Sausage', 'Kiełbasa', 'kielbaski'],
  ['White sausage', 'Biała kiełbasa'],
  ['Silesian sausage', 'Kiełbasa śląska'],
  ['Krakow sausage', 'Kiełbasa krakowska'],
  ['Country sausage', 'Kiełbasa wiejska'],
  ['Hunter sausage', 'Kiełbasa myśliwska'],
  ['Homemade-style sausage', 'Kiełbasa swojska'],
  ['Chicken sausage', 'Kiełbasa drobiowa'],
  ['Kabanos', 'Kabanosy'],
  ['Frankfurters', 'Parówki', 'hotdog'],
  ['Cocktail sausages', 'Kiełbaski koktajlowe'],
  ['Chorizo', 'Chorizo'],
  ['Black pudding', 'Kaszanka', 'krupniok'],

  // cold cuts
  ['Cold cuts', 'Wędliny', 'wedlina'],
  ['Ham', 'Szynka'],
  ['Smoked ham', 'Szynka wędzona'],
  ['Turkey ham', 'Szynka z indyka'],
  ['Prosciutto', 'Szynka parmeńska', 'parma'],
  ['Bacon', 'Boczek'],
  ['Smoked pork belly', 'Boczek wędzony'],
  ['Smoked pork loin', 'Polędwica sopocka'],
  ['Roast pork loin', 'Schab pieczony'],
  ['Sliced poultry loin', 'Polędwica drobiowa'],
  ['Salami', 'Salami'],
  ['Pepperoni', 'Pepperoni'],
  ['Mortadella', 'Mortadela'],
  ['Pâté', 'Pasztet'],
  ['Liver sausage', 'Pasztetowa'],
  ['Head cheese', 'Salceson'],
];
