import type { CatalogEntry } from './types';

export const PANTRY: readonly CatalogEntry[] = [
  // flour and starch
  ['Flour', 'Mąka'],
  ['Potato starch', 'Mąka ziemniaczana'],
  ['Cornflour', 'Mąka kukurydziana'],
  ['Rye flour', 'Mąka żytnia'],
  ['Spelt flour', 'Mąka orkiszowa'],
  ['Wholemeal flour', 'Mąka razowa'],
  ['Rice flour', 'Mąka ryżowa'],
  ['Buckwheat flour', 'Mąka gryczana'],
  ['Chickpea flour', 'Mąka z ciecierzycy'],
  ['Almond flour', 'Mąka migdałowa'],
  ['Coconut flour', 'Mąka kokosowa'],

  // baking
  ['Baking powder', 'Proszek do pieczenia'],
  ['Baking soda', 'Soda oczyszczona'],
  ['Yeast', 'Drożdże'],
  ['Gelatin', 'Żelatyna'],
  ['Vanilla sugar', 'Cukier waniliowy'],
  ['Vanilla extract', 'Ekstrakt waniliowy', 'wanilia'],
  ['Vanilla pod', 'Laska wanilii', 'wanilia'],
  ['Citric acid', 'Kwasek cytrynowy'],
  ['Pudding powder', 'Budyń w proszku'],
  ['Jelly', 'Galaretka'],
  ['Kisiel', 'Kisiel'],
  ['Baking chocolate', 'Czekolada do pieczenia'],
  ['Chocolate chips', 'Kropelki czekoladowe'],
  ['Sprinkles', 'Posypka do ciast'],
  ['Candied orange peel', 'Skórka pomarańczowa'],
  ['Marzipan', 'Marcepan'],
  ['Pancake mix', 'Mieszanka na naleśniki'],
  ['Panko', 'Panko'],

  // sugar and sweeteners
  ['Sugar', 'Cukier'],
  ['Icing sugar', 'Cukier puder', 'powdered'],
  ['Brown sugar', 'Cukier brązowy'],
  ['Cane sugar', 'Cukier trzcinowy'],
  ['Sugar cubes', 'Cukier w kostkach'],
  ['Jam sugar', 'Cukier żelujący'],
  ['Sweetener', 'Słodzik'],
  ['Xylitol', 'Ksylitol'],
  ['Stevia', 'Stewia'],
  ['Maple syrup', 'Syrop klonowy'],

  // salt and pepper
  ['Salt', 'Sól'],
  ['Salt, pepper', 'Sól, pieprz'],
  ['Sea salt', 'Sól morska'],
  ['Black pepper', 'Pieprz czarny'],
  ['White pepper', 'Pieprz biały'],
  ['Peppercorns', 'Pieprz ziarnisty'],

  // spices
  ['Paprika', 'Papryka słodka'],
  ['Smoked paprika', 'Papryka wędzona'],
  ['Hot paprika', 'Papryka ostra'],
  ['Chilli flakes', 'Płatki chilli'],
  ['Cayenne pepper', 'Pieprz cayenne'],
  ['Cumin', 'Kmin rzymski'],
  ['Caraway', 'Kminek'],
  ['Turmeric', 'Kurkuma'],
  ['Cinnamon', 'Cynamon'],
  ['Ground ginger', 'Imbir mielony'],
  ['Nutmeg', 'Gałka muszkatołowa'],
  ['Cloves', 'Goździki'],
  ['Cardamom', 'Kardamon'],
  ['Allspice', 'Ziele angielskie'],
  ['Bay leaves', 'Liście laurowe'],
  ['Juniper berries', 'Jagody jałowca'],
  ['Star anise', 'Anyż gwiazdkowy'],
  ['Saffron', 'Szafran'],
  ['Mustard seeds', 'Gorczyca'],
  ['Garlic powder', 'Czosnek granulowany'],
  ['Onion powder', 'Cebula granulowana'],
  ['Curry', 'Curry'],
  ['Garam masala', 'Garam masala'],
  ['Gingerbread spice', 'Przyprawa do piernika'],
  ['Grill seasoning', 'Przyprawa do grilla'],
  ['Chicken seasoning', 'Przyprawa do kurczaka'],
  ['Vegetable seasoning', 'Przyprawa warzywna'],
  ['Liquid seasoning', 'Przyprawa w płynie', 'maggi'],

  // dried herbs
  ['Marjoram', 'Majeranek'],
  ['Oregano', 'Oregano'],
  ['Dried basil', 'Bazylia suszona'],
  ['Dried thyme', 'Tymianek suszony'],
  ['Dried parsley', 'Pietruszka suszona'],
  ['Dried dill', 'Koperek suszony'],
  ['Dried lovage', 'Lubczyk suszony'],
  ['Provençal herbs', 'Zioła prowansalskie'],
  ['Italian herbs', 'Zioła włoskie'],
  ['Dried mushrooms', 'Grzyby suszone'],

  // stock and soups
  ['Stock cubes', 'Kostki rosołowe'],
  ['Vegetable stock', 'Bulion warzywny'],
  ['Chicken stock', 'Bulion drobiowy'],
  ['Instant noodle soup', 'Zupa błyskawiczna', 'ramen chinska'],
  ['Packet soup', 'Zupa w proszku'],
  ['Borscht concentrate', 'Koncentrat barszczu czerwonego'],
  ['Sour rye soup base', 'Zakwas na żurek'],

  // oil and vinegar
  ['Rapeseed oil', 'Olej rzepakowy'],
  ['Olive oil', 'Oliwa z oliwek'],
  ['Sunflower oil', 'Olej słonecznikowy'],
  ['Vegetable oil', 'Olej roślinny'],
  ['Coconut oil', 'Olej kokosowy'],
  ['Sesame oil', 'Olej sezamowy'],
  ['Lard', 'Smalec'],
  ['Vinegar', 'Ocet'],
  ['Apple cider vinegar', 'Ocet jabłkowy'],
  ['Wine vinegar', 'Ocet winny'],
  ['Balsamic vinegar', 'Ocet balsamiczny'],

  // pasta
  ['Pasta', 'Makaron'],
  ['Spaghetti', 'Spaghetti'],
  ['Penne', 'Penne'],
  ['Fusilli', 'Świderki'],
  ['Farfalle', 'Kokardki'],
  ['Tagliatelle', 'Tagliatelle'],
  ['Macaroni', 'Makaron rurki'],
  ['Lasagne sheets', 'Płaty lasagne'],
  ['Soup noodles', 'Makaron nitki'],
  ['Egg noodles', 'Makaron jajeczny'],
  ['Rice noodles', 'Makaron ryżowy'],
  ['Wholewheat pasta', 'Makaron razowy'],
  ['Gluten-free pasta', 'Makaron bezglutenowy'],
  ['Gnocchi', 'Gnocchi'],

  // rice and groats
  ['Rice', 'Ryż'],
  ['Basmati rice', 'Ryż basmati'],
  ['Jasmine rice', 'Ryż jaśminowy'],
  ['Brown rice', 'Ryż brązowy'],
  ['Arborio rice', 'Ryż arborio'],
  ['Sushi rice', 'Ryż do sushi'],
  ['Wild rice', 'Ryż dziki'],
  ['Boil-in-bag rice', 'Ryż w torebkach'],
  ['Buckwheat', 'Kasza gryczana'],
  ['White buckwheat', 'Kasza gryczana biała'],
  ['Millet', 'Kasza jaglana', 'jaglanka'],
  ['Semolina', 'Kasza manna'],
  ['Barley groats', 'Kasza jęczmienna'],
  ['Pearl barley', 'Pęczak'],
  ['Corn grits', 'Kasza kukurydziana', 'polenta'],
  ['Spelt groats', 'Kasza orkiszowa'],
  ['Bulgur', 'Kasza bulgur'],
  ['Couscous', 'Kuskus'],
  ['Quinoa', 'Komosa ryżowa', 'kinoa'],

  // cereals
  ['Rolled oats', 'Płatki owsiane', 'owsianka porridge'],
  ['Muesli', 'Muesli'],
  ['Granola', 'Granola'],
  ['Cornflakes', 'Płatki kukurydziane'],
  ['Oat bran', 'Otręby owsiane'],

  // pulses
  ['Red lentils', 'Soczewica czerwona'],
  ['Green lentils', 'Soczewica zielona'],
  ['Dried white beans', 'Fasola biała sucha'],
  ['Dried chickpeas', 'Ciecierzyca sucha'],
  ['Dried peas', 'Groch'],
  ['Split peas', 'Groch łuskany'],

  // tins
  ['Canned tomatoes', 'Pomidory w puszce', 'krojone'],
  ['Passata', 'Passata', 'przecier'],
  ['Tomato paste', 'Koncentrat pomidorowy'],
  ['Sun-dried tomatoes', 'Suszone pomidory'],
  ['Canned sweetcorn', 'Kukurydza konserwowa'],
  ['Canned peas', 'Groszek konserwowy'],
  ['Canned kidney beans', 'Fasola czerwona w puszce'],
  ['Canned white beans', 'Fasola biała w puszce'],
  ['Canned chickpeas', 'Ciecierzyca w puszce'],
  ['Baked beans', 'Fasolka po bretońsku'],
  ['Coconut milk', 'Mleko kokosowe'],
  ['Canned pineapple', 'Ananas w puszce'],
  ['Canned peaches', 'Brzoskwinie w puszce'],
  ['Canned tuna', 'Tuńczyk w puszce'],
  ['Canned sardines', 'Sardynki w puszce'],
  ['Mackerel in tomato sauce', 'Makrela w sosie pomidorowym'],
  ['Sprats in oil', 'Szprotki w oleju'],
  ['Anchovies', 'Anchois', 'sardele'],
  ['Luncheon meat', 'Mielonka'],
  ['Tinned meat', 'Konserwa turystyczna'],

  // jars
  ['Pickled cucumbers', 'Ogórki konserwowe', 'gherkins'],
  ['Dill pickles', 'Ogórki kiszone'],
  ['Sauerkraut', 'Kapusta kiszona'],
  ['Cooked beetroot', 'Buraczki'],
  ['Beetroot with horseradish', 'Ćwikła'],
  ['Marinated peppers', 'Papryka marynowana'],
  ['Marinated mushrooms', 'Grzybki marynowane'],
  ['Green olives', 'Oliwki zielone'],
  ['Black olives', 'Oliwki czarne'],
  ['Capers', 'Kapary'],
  ['Bigos', 'Bigos'],
  ['Lecho', 'Leczo'],
  ['Ajvar', 'Ajwar'],
  ['Hummus', 'Hummus'],

  // sauces and condiments
  ['Ketchup', 'Ketchup'],
  ['Mayonnaise', 'Majonez'],
  ['Mustard', 'Musztarda'],
  ['Dijon mustard', 'Musztarda dijon'],
  ['Sarepska mustard', 'Musztarda sarepska'],
  ['Horseradish', 'Chrzan'],
  ['Tartar sauce', 'Sos tatarski'],
  ['Garlic sauce', 'Sos czosnkowy'],
  ['Soy sauce', 'Sos sojowy'],
  ['Worcestershire sauce', 'Sos worcestershire'],
  ['Hot sauce', 'Sos ostry'],
  ['Sweet chilli sauce', 'Sos słodkie chilli'],
  ['BBQ sauce', 'Sos BBQ'],
  ['Tomato sauce', 'Sos pomidorowy'],
  ['Pasta sauce', 'Sos do spaghetti'],
  ['Pizza sauce', 'Sos do pizzy'],
  ['Pesto', 'Pesto'],
  ['Salsa', 'Salsa'],
  ['Salad dressing', 'Sos sałatkowy'],

  // spreads and sweet
  ['Honey', 'Miód'],
  ['Jam', 'Dżem'],
  ['Strawberry jam', 'Dżem truskawkowy'],
  ['Plum butter', 'Powidła śliwkowe'],
  ['Marmalade', 'Marmolada'],
  ['Raspberry syrup', 'Syrop malinowy'],
  ['Chocolate spread', 'Krem czekoladowy', 'nutella'],
  ['Peanut butter', 'Masło orzechowe'],
  ['Tahini', 'Tahini'],
  ['Dulce de leche', 'Masa krówkowa', 'kajmak'],
  ['Milk powder', 'Mleko w proszku'],

  // nuts, seeds and dried fruit
  ['Walnuts', 'Orzechy włoskie'],
  ['Hazelnuts', 'Orzechy laskowe'],
  ['Almonds', 'Migdały'],
  ['Flaked almonds', 'Płatki migdałowe'],
  ['Cashews', 'Orzechy nerkowca'],
  ['Peanuts', 'Orzeszki ziemne', 'arachidowe'],
  ['Pistachios', 'Pistacje'],
  ['Pecans', 'Orzechy pekan'],
  ['Pine nuts', 'Orzeszki piniowe'],
  ['Mixed nuts', 'Mieszanka orzechów'],
  ['Nut and dried fruit mix', 'Bakalie'],
  ['Sesame seeds', 'Sezam'],
  ['Poppy seeds', 'Mak'],
  ['Sunflower seeds', 'Słonecznik'],
  ['Pumpkin seeds', 'Pestki dyni'],
  ['Linseed', 'Siemię lniane', 'flaxseed'],
  ['Chia seeds', 'Nasiona chia'],
  ['Coconut flakes', 'Wiórki kokosowe'],
  ['Raisins', 'Rodzynki'],
  ['Dried apricots', 'Morele suszone'],
  ['Prunes', 'Suszone śliwki'],
  ['Dried figs', 'Figi suszone'],
  ['Dates', 'Daktyle'],
  ['Dried cranberries', 'Żurawina suszona'],

  // ready-made helpers
  ['Instant mashed potatoes', 'Puree ziemniaczane w proszku'],
];
