import type { CatalogEntry } from './types';

export const PRODUCE: readonly CatalogEntry[] = [
  // tomatoes, cucumbers, peppers
  ['Tomatoes', 'Pomidory'],
  ['Cherry tomatoes', 'Pomidory koktajlowe', 'pomidorki'],
  ['Beefsteak tomatoes', 'Pomidory malinowe'],
  ['Cucumbers', 'Ogórki'],
  ['Bell peppers', 'Papryka'],
  ['Red peppers', 'Papryka czerwona'],
  ['Yellow peppers', 'Papryka żółta'],
  ['Green peppers', 'Papryka zielona'],
  ['Chilli peppers', 'Papryczki chilli', 'chili'],
  ['Courgettes', 'Cukinia', 'zucchini'],
  ['Aubergines', 'Bakłażan', 'eggplant'],

  // roots and tubers
  ['Potatoes', 'Ziemniaki', 'kartofle'],
  ['Young potatoes', 'Młode ziemniaki', 'kartofle'],
  ['Sweet potatoes', 'Bataty', 'slodkie ziemniaki'],
  ['Carrots', 'Marchew'],
  ['Beetroot', 'Buraki'],
  ['Young beetroot with leaves', 'Botwinka'],
  ['Parsley root', 'Korzeń pietruszki', 'pietruszka'],
  ['Celeriac', 'Seler'],
  ['Celery', 'Seler naciowy'],
  ['Radishes', 'Rzodkiewki'],
  ['Daikon', 'Rzodkiew biała'],
  ['Turnip', 'Rzepa'],
  ['Kohlrabi', 'Kalarepa'],
  ['Ginger', 'Imbir'],
  ['Horseradish root', 'Korzeń chrzanu'],

  // onions and garlic
  ['Onions', 'Cebula'],
  ['Red onions', 'Cebula czerwona'],
  ['Shallots', 'Szalotki'],
  ['Spring onions', 'Dymka', 'zielona cebulka'],
  ['Leeks', 'Por'],
  ['Garlic', 'Czosnek'],
  ['Wild garlic', 'Czosnek niedźwiedzi', 'ramsons'],

  // cabbages and brassicas
  ['Cabbage', 'Kapusta'],
  ['Young cabbage', 'Młoda kapusta'],
  ['Red cabbage', 'Kapusta czerwona'],
  ['Savoy cabbage', 'Kapusta włoska'],
  ['Chinese cabbage', 'Kapusta pekińska'],
  ['Pak choi', 'Pak choi', 'bok choy'],
  ['Cauliflower', 'Kalafior'],
  ['Broccoli', 'Brokuły'],
  ['Brussels sprouts', 'Brukselka'],
  ['Kale', 'Jarmuż'],

  // salad and leaves
  ['Lettuce', 'Sałata'],
  ['Iceberg lettuce', 'Sałata lodowa'],
  ['Romaine lettuce', 'Sałata rzymska'],
  ["Lamb's lettuce", 'Roszponka'],
  ['Arugula', 'Rukola', 'rocket'],
  ['Mixed salad leaves', 'Mieszanka sałat'],
  ['Spinach', 'Szpinak'],
  ['Swiss chard', 'Boćwina'],
  ['Sorrel', 'Szczaw'],
  ['Chicory', 'Cykoria'],
  ['Radicchio', 'Radicchio'],
  ['Cress', 'Rzeżucha'],
  ['Sprouts', 'Kiełki'],
  ['Bean sprouts', 'Kiełki fasoli mung'],

  // other vegetables
  ['Pumpkin', 'Dynia'],
  ['Butternut squash', 'Dynia piżmowa'],
  ['Hokkaido pumpkin', 'Dynia hokkaido'],
  ['Corn on the cob', 'Kukurydza', 'sweetcorn'],
  ['Green beans', 'Fasolka szparagowa'],
  ['Fresh peas', 'Groszek zielony'],
  ['Broad beans', 'Bób'],
  ['Asparagus', 'Szparagi'],
  ['Artichoke', 'Karczoch'],
  ['Fennel', 'Koper włoski'],

  // mushrooms
  ['Mushrooms', 'Pieczarki', 'grzyby champignon'],
  ['Portobello mushrooms', 'Pieczarki portobello'],
  ['Oyster mushrooms', 'Boczniaki'],
  ['Shiitake', 'Shiitake'],
  ['Chanterelles', 'Kurki'],
  ['Porcini', 'Borowiki', 'prawdziwki grzyby'],

  // fresh herbs
  ['Dill', 'Koperek'],
  ['Parsley', 'Natka pietruszki', 'pietruszka'],
  ['Chives', 'Szczypiorek'],
  ['Basil', 'Bazylia'],
  ['Mint', 'Mięta'],
  ['Coriander', 'Kolendra', 'cilantro'],
  ['Thyme', 'Tymianek'],
  ['Rosemary', 'Rozmaryn'],
  ['Sage', 'Szałwia'],
  ['Lovage', 'Lubczyk'],
  ['Tarragon', 'Estragon'],
  ['Lemongrass', 'Trawa cytrynowa'],

  // everyday fruit
  ['Apples', 'Jabłka'],
  ['Pears', 'Gruszki'],
  ['Bananas', 'Banany'],
  ['Oranges', 'Pomarańcze'],
  ['Mandarins', 'Mandarynki', 'tangerines'],
  ['Clementines', 'Klementynki'],
  ['Lemons', 'Cytryny'],
  ['Limes', 'Limonki'],
  ['Grapefruit', 'Grejpfrut'],
  ['Pomelo', 'Pomelo'],
  ['Grapes', 'Winogrona'],
  ['Kiwi', 'Kiwi'],
  ['Pineapple', 'Ananas'],
  ['Mango', 'Mango'],
  ['Avocado', 'Awokado'],
  ['Watermelon', 'Arbuz'],
  ['Melon', 'Melon'],
  ['Pomegranate', 'Granat'],
  ['Figs', 'Figi'],
  ['Passion fruit', 'Marakuja'],
  ['Papaya', 'Papaja'],
  ['Persimmon', 'Persymona', 'kaki'],
  ['Dragon fruit', 'Pitaja'],
  ['Lychee', 'Liczi'],
  ['Physalis', 'Miechunka'],
  ['Coconut', 'Kokos'],
  ['Quince', 'Pigwa'],

  // stone fruit and berries
  ['Strawberries', 'Truskawki'],
  ['Raspberries', 'Maliny'],
  ['Blueberries', 'Borówki', 'jagody'],
  ['Blackberries', 'Jeżyny'],
  ['Redcurrants', 'Porzeczki czerwone'],
  ['Blackcurrants', 'Porzeczki czarne'],
  ['Gooseberries', 'Agrest'],
  ['Cranberries', 'Żurawina'],
  ['Chokeberries', 'Aronia'],
  ['Sweet cherries', 'Czereśnie'],
  ['Sour cherries', 'Wiśnie'],
  ['Plums', 'Śliwki'],
  ['Mirabelle plums', 'Mirabelki'],
  ['Greengages', 'Renklody'],
  ['Apricots', 'Morele'],
  ['Peaches', 'Brzoskwinie'],
  ['Nectarines', 'Nektarynki'],
  ['Rhubarb', 'Rabarbar'],
  ['Chestnuts', 'Kasztany'],
];
