import type { CatalogEntry } from './types';

export const SNACKS: readonly CatalogEntry[] = [
  // chocolate
  ['Chocolate', 'Czekolada'],
  ['Milk chocolate', 'Czekolada mleczna'],
  ['Dark chocolate', 'Czekolada gorzka'],
  ['White chocolate', 'Czekolada biała'],
  ['Chocolate with nuts', 'Czekolada z orzechami'],
  ['Chocolate bars', 'Batoniki czekoladowe'],
  ['Box of chocolates', 'Bombonierka'],
  ['Pralines', 'Praliny'],
  ['Chocolate dragées', 'Draże czekoladowe'],
  ['Soufflé chocolates', 'Ptasie mleczko'],

  // sweets
  ['Sweets', 'Cukierki'],
  ['Gummy bears', 'Żelki'],
  ['Sour gummies', 'Kwaśne żelki'],
  ['Hard candy', 'Cukierki twarde'],
  ['Fudge', 'Krówki'],
  ['Caramels', 'Karmelki'],
  ['Mints', 'Cukierki miętowe'],
  ['Lollipops', 'Lizaki'],
  ['Marshmallows', 'Pianki'],
  ['Liquorice', 'Lukrecja'],
  ['Toffees', 'Toffi'],
  ['Chocolate sweets', 'Cukierki czekoladowe'],
  ['Chocolate-coated jellies', 'Galaretki w czekoladzie'],
  ['Pastilles', 'Pastylki'],
  ['Chewing gum', 'Guma do żucia'],
  ['Sugar-free gum', 'Guma bez cukru'],
  ['Halva', 'Chałwa'],
  ['Sesame snaps', 'Sezamki'],
  ['Meringues', 'Bezy'],
  ['Coconut macaroons', 'Kokosanki'],
  ['Gingerbread cookies', 'Pierniczki'],
  ['Chocolate-coated gingerbread', 'Pierniki w czekoladzie'],

  // biscuits and wafers
  ['Biscuits', 'Herbatniki'],
  ['Cookies', 'Ciastka', 'ciasteczka'],
  ['Chocolate chip cookies', 'Ciastka z kawałkami czekolady'],
  ['Butter biscuits', 'Ciastka maślane'],
  ['Shortbread', 'Kruche ciasteczka'],
  ['Chocolate-coated biscuits', 'Ciastka w czekoladzie'],
  ['Digestive biscuits', 'Ciastka pełnoziarniste'],
  ['Oat biscuits', 'Ciastka owsiane'],
  ['Cream sandwich biscuits', 'Ciastka z kremem'],
  ['Jelly biscuits', 'Ciastka z galaretką'],
  ['Wafers', 'Wafle'],
  ['Wafer bars', 'Wafelki'],
  ['Wafer rolls', 'Rurki waflowe'],
  ['Rice cakes', 'Wafle ryżowe'],
  ['Gluten-free cookies', 'Ciastka bezglutenowe'],
  ['Waffles', 'Gofry'],

  // crisps and salty
  ['Crisps', 'Chipsy'],
  ['Tortilla chips', 'Nachosy'],
  ['Corn puffs', 'Chrupki kukurydziane'],
  ['Peanut puffs', 'Chrupki orzechowe'],
  ['Cheese puffs', 'Chrupki serowe'],
  ['Crackers', 'Krakersy'],
  ['Cheese crackers', 'Krakersy serowe'],
  ['Rice crackers', 'Chrupki ryżowe'],
  ['Pretzel sticks', 'Paluszki słone'],
  ['Pretzel snacks', 'Precelki'],
  ['Popcorn', 'Popcorn'],
  ['Microwave popcorn', 'Popcorn do mikrofalówki'],
  ['Beef jerky', 'Suszone mięso'],

  // nuts and mixes
  ['Salted peanuts', 'Orzeszki solone'],
  ['Salted pistachios', 'Pistacje solone'],
  ['Roasted cashews', 'Orzechy nerkowca prażone'],
  ['Roasted almonds', 'Migdały prażone'],
  ['Roasted nut mix', 'Mieszanka orzechów prażonych'],
  ['Trail mix', 'Mieszanka studencka'],
  ['Salted sunflower seeds', 'Słonecznik prażony'],
  ['Roasted chickpeas', 'Ciecierzyca prażona'],
  ['Chocolate-covered raisins', 'Rodzynki w czekoladzie'],

  // bars and fruit snacks
  ['Cereal bars', 'Batony zbożowe'],
  ['Protein bars', 'Batony proteinowe'],
  ['Fruit bars', 'Batony owocowe'],
  ['Nut bars', 'Batony orzechowe'],
  ['Dried fruit chips', 'Chipsy owocowe'],
  ['Fruit mousse pouch', 'Mus owocowy w saszetce'],
];
