import type { CatalogEntry } from './types';

export const SUPPLEMENTS: readonly CatalogEntry[] = [
  ['Whey protein','Białko serwatkowe','wpc'],
  ['Whey isolate','Izolat białka serwatkowego','wpi'],
  ['Plant protein','Białko roślinne'],
  ['Creatine monohydrate','Monohydrat kreatyny'],
  ['Pre-workout powder','Przedtreningówka'],
  ['Electrolytes','Elektrolity'],
  ['Multivitamins','Multiwitamina'],
  ['Vitamin D3','Witamina D3'],
  ['Vitamin C','Witamina C'],
  ['Vitamin B12','Witamina B12'],
  ['Magnesium','Magnez'],
  ['Omega-3','Omega-3'],
  ['Collagen','Kolagen'],
  ['Zinc','Cynk'],
  ['Iron','Żelazo'],
  ['Calcium','Wapń'],
  ['Probiotics','Probiotyki'],
  ['Fish oil','Olej rybi'],
  ['Energy gels','Żele energetyczne'],
  ['Mass gainer','Odżywka węglowodanowo-białkowa'],
  ['Casein','Kazeina'],
  ['Whey hydrolysate','Hydrolizat białka serwatkowego','wph'],
  ['Pea protein','Białko grochu'],
  ['Rice protein','Białko ryżowe'],
  ['Soy protein','Białko sojowe'],
  ['Creatine malate','Jabłczan kreatyny'],
  ['BCAA','BCAA'],
  ['EAA','EAA'],
  ['Beta-alanine','Beta-alanina'],
  ['Citrulline','Cytrulina'],
  ['Citrulline malate','Jabłczan cytruliny'],
  ['Arginine','Arginina'],
  ['Glutamine','Glutamina'],
  ['Taurine','Tauryna'],
  ['Carnitine','L-karnityna'],
  ['HMB','HMB'],
  ['Carbohydrate powder','Odżywka węglowodanowa'],
  ['Isotonic powder','Izotonik w proszku'],
  ['Electrolyte tablets','Elektrolity w tabletkach'],
  ['Caffeine capsules','Kofeina w kapsułkach'],
  ['Vitamin A','Witamina A'],
  ['Vitamin E','Witamina E'],
  ['Vitamin K2','Witamina K2'],
  ['Vitamin D3 and K2','Witamina D3 i K2','d3k2'],
  ['Vitamin B complex','Witaminy z grupy B'],
  ['Vitamin B6','Witamina B6'],
  ['Folic acid','Kwas foliowy','foliany'],
  ['Biotin','Biotyna'],
  ['Potassium','Potas'],
  ['Selenium','Selen'],
  ['Copper','Miedź'],
  ['Iodine','Jod'],
  ['Chromium','Chrom'],
  ['Magnesium citrate','Cytrynian magnezu'],
  ['Magnesium bisglycinate','Bisglicynian magnezu','diglicynian'],
  ['Magnesium with B6','Magnez z B6'],
  ['Zinc picolinate','Pikolinian cynku'],
  ['Cod liver oil','Tran'],
  ['Marine collagen','Kolagen morski'],
  ['Hydrolyzed collagen','Kolagen hydrolizowany'],
  ['Glucosamine','Glukozamina'],
  ['Chondroitin','Chondroityna'],
  ['MSM','MSM','metylosulfonylometan'],
  ['Hyaluronic acid','Kwas hialuronowy'],
  ['Coenzyme Q10','Koenzym Q10','ubichinon'],
  ['Lutein','Luteina'],
  ['Prebiotics','Prebiotyki'],
  ['Inulin','Inulina'],
  ['Ashwagandha','Ashwagandha','witania'],
  ['Melatonin','Melatonina'],
];

